### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by deltabeard** [libretro/libretro-mpv#16]
I get a blank screen and a crash when trying to open a video on Windows when testing the new Render API.

**Comment by deltabeard** [comment]
Tested working on WIndows 8.1 when loading the core and a video file from within the Retroarch GUI launched from MSYS2-Mingw64.

Running `gdb --args ../RetroArch/retroarch.exe -L ./mpv_libretro.dll file.mkv` produces the following segmentation fault:

```
Thread 10 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 5128.0x6ec]
0x00007fff781fb86e in ntdll!RtlEnterCriticalSection ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007fff781fb86e in ntdll!RtlEnterCriticalSection ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000037c5996 in m_pthread_mutex_lock (mutex=mutex@entry=0x338d430)
    at ../osdep/win32/pthread.c:59
#2  0x00000000037bba15 in kill_cb (ptr=0x338d3c0)
    at ../video/out/vo_libmpv.c:252
#3  0x0000000003738bf2 in mp_dispatch_queue_process (queue=0x18593a0,
    timeout=0.044451999999999006) at ../misc/dispatch.c:280
#4  0x000000000376bc46 in mp_wait_events (mpctx=0x1858eb0)
    at ../player/playloop.c:60
#5  0x000000000376dbae in run_playloop (mpctx=0x1858eb0)
    at ../player/playloop.c:1118
#6  0x000000000376528c in play_current_file (mpctx=0x1858eb0)
    at ../player/loadfile.c:1368
#7  mp_play_files (mpctx=mpctx@entry=0x1858eb0) at ../player/loadfile.c:1539
#8  0x0000000003750248 in core_thread (p=p@entry=0x1858eb0)
    at ../player/client.c:524
#9  0x00000000037c5be9 in run_thread (lpParameter=<optimized out>)
    at ../osdep/win32/pthread.c:214
#10 0x00007fff762a13d2 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#11 0x00007fff781d54f4 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#12 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

When no file is specified, such as `gdb --args ../RetroArch/retroarch.exe -L ./mpv_libretro.dll`, the following segmentation fault occurs:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fff75f611f1 in strlen () from C:\Windows\system32\msvcrt.dll
(gdb) bt
#0  0x00007fff75f611f1 in strlen () from C:\Windows\system32\msvcrt.dll
#1  0x000000000048bd73 in strcpy_alloc ()
#2  0x000000000048b90a in set_load_content_info ()
#3  0x0000000000402617 in core_load_game ()
#4  0x000000000041c320 in content_init ()
#5  0x000000000040cad0 in command_event ()
#6  0x00000000004074f8 in retroarch_main_init ()
#7  0x0000000000418c30 in content_load ()
#8  0x00000000004190de in task_load_content ()
#9  0x000000000041962f in task_load_content_callback.constprop ()
#10 0x000000000040177e in rarch_main ()
#11 0x0000000000803c88 in main_getcmdline ()
#12 0x00000000004013c7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:331
#13 0x00000000004014cb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:187
```
